<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-09-21T00:00:06 IST" name="LoginSuite" finished-at="2025-09-21T00:00:13 IST" duration-ms="6881">
    <groups>
      <group name="regression">
        <method signature="LoginTest.testInvalidLogin()[pri:0, instance:com.qa.parabank.tests.LoginTest@2e4b8173]" name="testInvalidLogin" class="com.qa.parabank.tests.LoginTest"/>
        <method signature="LoginTest.testValidLogin()[pri:0, instance:com.qa.parabank.tests.LoginTest@2e4b8173]" name="testValidLogin" class="com.qa.parabank.tests.LoginTest"/>
      </group> <!-- regression -->
      <group name="sanity">
        <method signature="LoginTest.testInvalidLogin()[pri:0, instance:com.qa.parabank.tests.LoginTest@2e4b8173]" name="testInvalidLogin" class="com.qa.parabank.tests.LoginTest"/>
        <method signature="LoginTest.testValidLogin()[pri:0, instance:com.qa.parabank.tests.LoginTest@2e4b8173]" name="testValidLogin" class="com.qa.parabank.tests.LoginTest"/>
      </group> <!-- sanity -->
    </groups>
    <test started-at="2025-09-21T00:00:06 IST" name="LoginTest" finished-at="2025-09-21T00:00:13 IST" duration-ms="6881">
      <class name="com.qa.parabank.tests.LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.qa.parabank.tests.LoginTest@2e4b8173]" started-at="2025-09-21T00:00:06 IST" name="setup" finished-at="2025-09-21T00:00:09 IST" duration-ms="3539" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testInvalidLogin()[pri:0, instance:com.qa.parabank.tests.LoginTest@2e4b8173]" started-at="2025-09-21T00:00:09 IST" name="testInvalidLogin" finished-at="2025-09-21T00:00:10 IST" duration-ms="127" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://parabank.parasoft.com/parabank/overview.htm] but found [https://parabank.parasoft.com/parabank/index.htm;jsessionid=64C6AD32F76F3B7E13EADFC0B12A5DDE]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://parabank.parasoft.com/parabank/overview.htm] but found [https://parabank.parasoft.com/parabank/index.htm;jsessionid=64C6AD32F76F3B7E13EADFC0B12A5DDE]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.qa.parabank.tests.LoginTest.testInvalidLogin(LoginTest.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.qa.parabank.tests.LoginTest@2e4b8173]" started-at="2025-09-21T00:00:10 IST" name="tearDown" finished-at="2025-09-21T00:00:10 IST" duration-ms="90" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.qa.parabank.tests.LoginTest@2e4b8173]" started-at="2025-09-21T00:00:10 IST" name="setup" finished-at="2025-09-21T00:00:13 IST" duration-ms="2797" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testValidLogin()[pri:0, instance:com.qa.parabank.tests.LoginTest@2e4b8173]" started-at="2025-09-21T00:00:13 IST" name="testValidLogin" finished-at="2025-09-21T00:00:13 IST" duration-ms="127" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://parabank.parasoft.com/parabank/overview.htm] but found [https://parabank.parasoft.com/parabank/index.htm;jsessionid=561FC821875A55EE7C67A3A937EABBCC]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://parabank.parasoft.com/parabank/overview.htm] but found [https://parabank.parasoft.com/parabank/index.htm;jsessionid=561FC821875A55EE7C67A3A937EABBCC]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.qa.parabank.tests.LoginTest.testValidLogin(LoginTest.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testValidLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.qa.parabank.tests.LoginTest@2e4b8173]" started-at="2025-09-21T00:00:13 IST" name="tearDown" finished-at="2025-09-21T00:00:13 IST" duration-ms="181" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.parabank.tests.LoginTest -->
    </test> <!-- LoginTest -->
  </suite> <!-- LoginSuite -->
</testng-results>
